A notebook for those useful, but easily forgetable tensorflow tricks. Only applicable for tf 2.x

In [1]:
# tensorflow 2.x
import tensorflow as tf

# Altering tensor shape
It is tempting to just use tf.reshape. But be careful! ```tf.reshape``` can mess up with the data.

**Rule of thumb**
- ```tf.transpose```: Just want to swap dimensions, and input dims = output dims.
- ```tf.squeeze```: Drop one dimension (whose value is 1).
- ```tf.expand_dims```: Add one dimension (whose value is 1).
- ```tf.reshape```: if all above not applicable.

In [11]:
# Transpose (permute) the given dimensions
x = tf.constant([[[1, 2, 3], [4, 5, 6]]])
print(x)
tf.transpose(x, perm=[0,2,1])

tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)


<tf.Tensor: id=26, shape=(1, 3, 2), dtype=int32, numpy=
array([[[1, 4],
        [2, 5],
        [3, 6]]])>

In [16]:
# Add / remove 1 dimension
x = tf.constant([[[1, 2, 3], [4, 5, 6]]])
print(x)
sqz = tf.squeeze(x, axis=[0])
print('\nAfter squeeze:', sqz)
xpd = tf.expand_dims(sqz, axis=0)
print('\nAfter expand:', xpd)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)

After squeeze: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

After expand: tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)


In [9]:
# reshape, note the output is NOT a transpose.
x = tf.constant([[[1, 2, 3], [4, 5, 6]]])
print(x)
tf.reshape(x, shape=(1,3,2))

tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)


<tf.Tensor: id=22, shape=(1, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4],
        [5, 6]]])>